// <auto-generated />
using System;
using BydPlatform.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BYDPlatform.Infrastructure.Migrations
{
    [DbContext(typeof(BydPlatformDbContext))]
    [Migration("20231218034618_AddFactory")]
    partial class AddFactory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BYDPlatform.Domain.Entities.RegisterFactory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id")
                        .HasComment("主键");

                    b.Property<int>("BuId")
                        .HasColumnType("int(11)")
                        .HasColumnName("bu_id")
                        .HasComment("所属事业部编号");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created")
                        .HasComment("创建时间");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by")
                        .HasComment("创建人");

                    b.Property<string>("FactoryName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("factory_name")
                        .HasComment("备案工厂名称");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_modified")
                        .HasComment("修改时间");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("last_modified_by")
                        .HasComment("上次修改时间");

                    b.Property<int>("Level")
                        .HasColumnType("int(2)")
                        .HasColumnName("factory_level")
                        .HasComment("工厂等级");

                    b.HasKey("Id");

                    b.ToTable("register_factory", null, t =>
                        {
                            t.HasComment("备案工厂表");
                        });
                });

            modelBuilder.Entity("BYDPlatform.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id")
                        .HasComment("id主键");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created")
                        .HasComment("创建时间");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by")
                        .HasComment("创建人");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_modified")
                        .HasComment("修改时间");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("last_modified_by")
                        .HasComment("上次修改时间");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("password")
                        .HasComment("密码");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("user_name")
                        .HasComment("用户名");

                    b.HasKey("Id");

                    b.ToTable("user", null, t =>
                        {
                            t.HasComment("用户表");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
